<?php

namespace App\Modules\User\Http\Controllers;

use App\Api\V1\Controllers\BaseController;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Modules\User\Http\Requests\CreatePermissionRequest;
use App\Modules\User\Models\permission;
use Yajra\Datatables\Datatables;
use DB;
class PermissionApiController extends BaseController
{
    public function store(CreatePermissionRequest $request){
        $data_add              = new permission($request->all());
        $data_add->save();
        return $this->responseCreated($data_add);
//    return view('welcome');
    }
    public function anyData(){
        $data     =permission::select();
//            ->with('position')
//            ->with('user');
        $dbResult = Datatables::of($data)
//            ->addColumn('email_phone', function ($dat) {
//                return $dat->user->email . '<br/>' . $dat->phone;
//            })
//            ->addColumn('type_name', function ($dat) {
//                $str = '';
//                if ($dat->type == User::$TYPE_WORK_FULL_TIME) {
//                    $str = 'Nhân Viên Chính Thức';
//                }
//                if ($dat->type == User::$TYPE_WORK_PART_TIME) {
//                    $str = 'Cộng tác viên';
//                }
//
//                return $str;
//            })
            ->addColumn('action', function ($data) {
                $action = '<a href="" class="btn btn-xs btn-success" title="Chi tiết"><i class="fa fa-eye"></i></a> &nbsp;';
                $action .= '<a href="javascript:setUpdate('.$data->id.')" class="btn btn-xs btn-primary" title="Chỉnh sửa"><i class="fa fa-edit"></i></a> &nbsp;';
                $action .= '<a href="javascript:setDelete('.$data->id.')" class="btn btn-xs btn-danger" title="Xóa"><i class="fa fa-times"></i> </a> &nbsp;';

                return $action;
            })
            ->make(TRUE);

        return $dbResult;
    }
    public function delete($id)
    {
       $data= new permission();
       $data->destroy($id);
        return parent::responseDeleted($data); // TODO: Change the autogenerated stub
    }
    public function getall_byrole($id){
        $data=\DB::table('permissions')
            ->join('permission_role','permissions.id','permission_role.permission_id')
            ->where('permission_role.role_id',$id)
            ->pluck('name')->toArray();
        return $data;
    }
}
